### PR TITLE
Implement expenses and expense manager

### PR DESCRIPTION
**Pull request by OKok-3**
Implemented the expenses entity and its UseCase. I've also added needed attribute and methods to User, UserManager to integrate Expenses into our program

### CODE REVIEW

**Comment by OKok-3** [comment]
It deviates slightly from our CRC model. In our CRC, we specified that ExpensesManager should have the calculateBalance method. But that would create unnecessary attributes for us to access the user's UserManager to get the expenses list. So I moved it over to UserManager.

I think this aligns with CLEAN arch. but I'm not too sure. Any suggestions would be highly appreciated!

**Comment by OKok-3** [comment]
Worked together with Bolade @cdw18

**Review by sarihammad — APPROVED** [review]
Looks good!

**Review by cdw18 — APPROVED** [review]
Expenses was not deleted but rather renamed to Expense without the s. Daniel's changes look good to me!

**Pull request merged**
