### PR TITLE
Implemented GetTodaysEvents

### PR DESCRIPTION
**Pull request by cdw18**
Implemented GetTodaysEvents for the main view and for sorting by date and priority. Not sure if I needed a constructor so I did not make one. Let me know if I should make one.

### CODE REVIEW

**Review by sarihammad — COMMENTED** [review]
I'm not sure if my thinking is correct, but I think it would be better if this was a method in one of the gateways.

**Comment by cdw18** [comment]
> I'm not sure if my thinking is correct, but I think it would be better if this was a method in one of the gateways.

I'm not sure. I looked up use cases examples and most seem to say that user's actions are use cases so getting the current day's list of events on the main view would be one of them (?). I could be wrong. Also I don't think Getaways can directly call use entity methods.

**Review by OKok-3 — CHANGES_REQUESTED** [review]
I agree that this is a use case, but I think it would be more appropriate to add it into the UserManager use case, since this is accessing the user entity and we have a specific use case for it already.

Otherwise everything else looks good!

**Comment by cdw18** [comment]
> I agree that this is a use case, but I think it would be more appropriate to add it into the UserManager use case, since this is accessing the user entity and we have a specific use case for it already.
> 
> Otherwise everything else looks good!

I think GetTodaysEvent should be kept as a separate class along with the other use cases. Looking at the examples from Clean Architecture, each class is separated by an action/responsibility. Also it will help with complying with the SOLID principles.

**Comment by OKok-3** [comment]
> > I agree that this is a use case, but I think it would be more appropriate to add it into the UserManager use case, since this is accessing the user entity and we have a specific use case for it already.
> > Otherwise everything else looks good!
> 
> I think GetTodaysEvent should be kept as a separate class along with the other use cases. Looking at the examples from Clean Architecture, each class is separated by an action/responsibility. Also it will help with complying with the SOLID principles.

Yeah that makes more sense. Thx for the clarification!

**Review by OKok-3 — APPROVED** [review]

**Review by sarihammad — APPROVED** [review]
👍

**Pull request merged**
