### PR TITLE
Event date comparator test

### PR DESCRIPTION
**Pull request by OKok-3**
Created some tests for `EventDateComparator`. Also corrected a logical error in the javadoc of `EventDateComparator`

### CODE REVIEW

**Review by cdw18 — DISMISSED** [review]
Looks good! Thanks for changing the javadoc by the way!

**Review by sarihammad — COMMENTED** [review]
The javadocs say 'before after' on line 18, other than that you're good

**Comment by OKok-3** [comment]
@sarihammad just fixed that, good catch!

**Review by sarihammad — APPROVED** [review]
👌

**Review by cdw18 — APPROVED** [review]

**Pull request merged**
