### PR TITLE
database-helper

### PR DESCRIPTION
**Pull request by sarihammad**
Implemented a basic database helper for storing events.

### CODE REVIEW

**Review by cdw18 — DISMISSED** [review]
Looks good to me!

**Review by OKok-3 — CHANGES_REQUESTED** [review]
I don't know if this is me specifically, but looking through the code in Android Studio had given me a warning saying "Value must be ≥ 0" regarding all `cur.getColumnIndex()` method. Would this be a problem?

**Comment by sarihammad** [comment]
Read online that it shouldn't be an issue, but I made changes anyway. Warning should disappear.

**Review by OKok-3 — APPROVED** [review]
Thanks for researching online, the warning is gone for me too. Thanks!

**Review by cdw18 — APPROVED** [review]

**Pull request merged**
