### PR TITLE
Fix social class

### PR DESCRIPTION
**Pull request by OKok-3**

### CODE REVIEW

**Review by sarihammad — CHANGES_REQUESTED** [review]
I'm not sure I'm reading the changes right, but I think lines 30 and 32 are duplicates. I think you might have instantiated location twice. Might be wrong though because I'm still unsure on how Github shows the changes.

**Review by cdw18 — CHANGES_REQUESTED** [review]
Like Sari said, lines 30 and 32 are the same. Otherwise, looks good!

**Comment by OKok-3** [comment]
Oops, sorry. Don't know how that got duplicated. It's fixed now!

**Review by sarihammad — APPROVED** [review]
👍

**Review by cdw18 — APPROVED** [review]
Looks good!

**Pull request merged**
