### PR TITLE
Assessment duration

### PR DESCRIPTION
**Pull request by cdw18**
Finished implementing Assessment class. Looking into better ways to calculate duration and found out Java had a Duration package which made far more simpler. Also implemented setStartDate and setEndDate so they calculate new duration each time one is called.

### CODE REVIEW

**Review by sarihammad — APPROVED** [review]
Looks good! You should also override setters for start and end date and use the same duration format for any other event types that have duration (I think Social is the only other one).

**Review by OKok-3 — COMMENTED** [review]
What is `@SuppressLint("DefaultLocale")` for on line 81?

**Comment by cdw18** [comment]
> What is `@SuppressLint("DefaultLocale")` for on line 81?

It's something that android studio suggested (I don't know why) for a warning/error that needed to be solved before I could commit and push. I do not know what that error was, it said something about DefaultLocale.

**Review by OKok-3 — APPROVED** [review]
Alright, thx for the clarification!

**Pull request merged**
